### ISSUE TITLE
Gran Turismo 4 - No interlacing patch not working ?

### ISSUE THREAD

**Issue by Scar557** [CookiePLMonster/Console-Cheat-Codes#5] opened 2021-08-19 01:48 UTC
Hello !

I recently discovered your blog and all of your work, and was very happy to discover a " No interlacing patch " for Gran Turismo 4 PAL ( Since they're usually only for NTSC since there's no progressive mode on PAL ).

Unfortnuately, it doesn't seem to work properly on my end, game seems to run in progressive mode according to PCSX2, but the in-game parts are still blurry as hell, even though i don't have any de-interlacing filter active.

Checked my ISO but as far as i know there wasn't no revisions of Gran Turismo 4 PAL, so i really don't know what could cause the problem.

**Comment by CookiePLMonster** [comment] 2021-08-19 07:53
Can you show a screenshot? If it runs in Progressive then I guess the patch works as intended, but maybe you just expect it to make things sharper than it reasonably can.

Also do note that this fake Progressive halves the resolution height (there are no true Progressive PAL resolutions), so you might need to ramp up upscaling a bit to compensate for that.

**Comment by Scar557** [comment] 2021-08-19 16:29
Okay so here it is : 

Keep in mind that i'm using a different patch by someone else for the NTSC port of the game, has side effects like, for example, the in-game looking a lot less vibrant, having colors a bit faded and all, but the deinterlacing works perfectly, so i wanted to use this as an example.

Here's the comparison, starting with the NTSC menu, followed by the PAL menu, no differences there : 

![NTSC menu](https://user-images.githubusercontent.com/43917158/130105849-bb292537-c50c-4b22-8c11-a937fc99f679.png)
![PAL menu](https://user-images.githubusercontent.com/43917158/130105852-e0279e0d-919c-4d72-a816-7f94454a64eb.png)

And now, the loading transition into the " in-game " part, you can clearly see when the window information at the top shows that the game switches to progressive mode, that the interlacing ( Or blurryness, call it how you like ) starts to show :

![NTSC transition to in-game](https://user-images.githubusercontent.com/43917158/130106507-ed8825d5-f091-461b-a9c5-77a3be826a99.png)
![PAL transition to in-game](https://user-images.githubusercontent.com/43917158/130106517-7859adaa-3003-46c6-a213-53fb0dc5fe29.png)

But it could just be a texture bug or an internal resolution difference, right ? 

So i tried comparing the in-game, NTSC at 3x resolution, and both 3x and 4x resolution for the PAL : 

![NTSC in-game](https://user-images.githubusercontent.com/43917158/130106744-26bf2dce-5a96-45f9-8c7f-a98880cd3a68.png)
![PAL in-game](https://user-images.githubusercontent.com/43917158/130106789-4827b6d9-1f62-4703-8744-d5ce9fa3e2a2.png)
![PAL in-game 2K](https://user-images.githubusercontent.com/43917158/130106816-ad174cde-430c-4925-867c-55fe711d0830.png)

As you can see, almost no differences between the 3x and 4x PAL screenshots, though the patched NTSC looks hella clean, crisp and sharp, if you can forget the little side effect with the colors being rendered like shit.

**Comment by CookiePLMonster** [comment] 2021-08-19 17:28
> But it could just be a texture bug or an internal resolution difference, right ?

Yes, this is the resolution difference I mentioned. At the moment I have no way of getting around it, as GT4 currently enters a PAL double strike mode, that is "progressive" but half height. Any truly progressive mode on the PS2 is 60 FPS, so that is a no-go on the PAL version.

> though the patched NTSC looks hella clean, crisp and sharp, if you can forget the little side effect with the colors being rendered like shit.

The color differences are actually a D3D11 PCSX2 bug, if you try OGL the colors will be identical.

**Comment by Scar557** [comment] 2021-08-19 18:58
But iv'e tried upscaling the internal resolution, as you can see in the last 3 screenshots, it doesn't change anything though.

And the " blurryness " is very characteristic, looks like interlacing to me ?

**Comment by CookiePLMonster** [comment] 2021-08-19 19:00
> And the " blurryness " is very characteristic, looks like interlacing to me ?

Considering "fake progressive" displays half of an interlaced image, this is very much possible. Again, I would love to improve that but at the moment I don't know if it's possible.

**Comment by Scar557** [comment] 2021-08-19 19:40
How does this work, by the way ?

NTSC can output progressive at all times but not PAL ? 

And what's " double-strike " ? 

Sorry, but i'm just trying to understand how this patch works.

**Comment by CookiePLMonster** [comment] 2021-08-19 20:47
> NTSC can output progressive at all times but not PAL ?

There are no 50 FPS progressive modes.


> And what's " double-strike " ?

It's a mode where every line is drawn twice, instead of being interlaced - hence half resolution height, but "progressive" visuals.

**Comment by CookiePLMonster** [comment] 2022-03-12 23:05
Closing since as far as I can tell it works as intended.

**Closed by CookiePLMonster** 2022-03-12 23:05 UTC

**Comment by Unix0815** [comment] 2022-03-16 20:55
You can get rid of the blurry image. Using the "Wild Arms Hack" in the graphics settings prevents the game from rendring doubled horizontal lines when upscaling the image.

**Comment by Unix0815** [comment] 2022-03-16 21:05
> > NTSC can output progressive at all times but not PAL ?
> 
> There are no 50 FPS progressive modes.
> 
> > And what's " double-strike " ?
> 
> It's a mode where every line is drawn twice, instead of being interlaced - hence half resolution height, but "progressive" visuals.

Gran Turismo 3 runs in full 640 x 512 in progressive Mode at 50 Hz.

**Comment by CookiePLMonster** [comment] 2022-03-16 21:15
> > There are no 50 FPS progressive modes.
> 
> Gran Turismo 3 runs in full 640 x 512 in progressive Mode at 50 Hz. Double the vertical resolution of GT4.

It technically does not run progressive -  the image is still interlaced, but output frames do not alternate lines.

**Comment by Unix0815** [comment] 2022-03-16 21:20
> > > There are no 50 FPS progressive modes.
> > 
> > 
> > Gran Turismo 3 runs in full 640 x 512 in progressive Mode at 50 Hz. Double the vertical resolution of GT4.
> 
> It technically does not run progressive - the image is still interlaced, but output frames do not alternate lines.

But wouldn't this half the framerate? The game still runs at full 50 fps and outputs all the lines in one frame. On real hardware, my interlaced only CRT TV can't display the signal anymore. If thats not the definition of a progressive signal, what is it then?

**Comment by Scar557** [comment] 2022-03-24 23:25
Aight, i've checked the " Wild Arms offsets " thing. 

Shit, it works ? 

I mean, somewhat, it's not full progressive, but it's already way better like this !

Only problem, is that it seems to affect the in-game fonts, the offsets seems fucked by a few pixels, like badly emulated N64 games, i guess Gran Turismo is dependant on this pixel-precision thing or something, or is there actually a workaround ?
